import React, { useEffect, useMemo, useRef, useState } from "react";
import {
  completeEmailVerification, completePasswordReset, getAgeVerification, getCurrentUser, getMemberProfile,
  login, logout, registerAccount, requestPasswordReset, resendVerification, submitAgeVerification,
} from "./lib/appwrite";

const languageKey = "jason-shadow-membership-language";
const initialLanguage = () => localStorage.getItem(languageKey) || (navigator.language?.startsWith("de") ? "de" : "en");
const messageFor = (error, t) => error?.message === "AGE_REQUIREMENT_NOT_MET" ? t.ageRejected : error?.message === "AGE_REQUEST_EXISTS" ? t.ageExists : (error?.message || t.genericError);

function Field({ label, ...props }) { return <label className="form-field"><span>{label}</span><input {...props} /></label>; }
function Tier({ number, title, text, featured }) { return <article className={`tier-card${featured ? " tier-card--featured" : ""}`}><span className="step-number">{number}</span><h3>{title}</h3><p>{text}</p></article>; }
function LockedCard({ t, wide }) { return <article className="locked-card"><div className={`locked-preview${wide ? " locked-preview--exclusive" : ""}`} aria-hidden="true"><span className="lock-icon">◇</span></div><div><p className="card-kicker">{t.previewLabel}</p><h3>{t.lockedTitle}</h3><p>{t.lockedText}</p></div></article>; }

function Modal({ title, eyebrow, onClose, children, t }) {
  const closeRef = useRef(null);
  useEffect(() => { closeRef.current?.focus(); const key = (e) => e.key === "Escape" && onClose(); document.addEventListener("keydown", key); document.body.classList.add("modal-open"); return () => { document.removeEventListener("keydown", key); document.body.classList.remove("modal-open"); }; }, [onClose]);
  return <div className="modal-backdrop" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><section className="process-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button ref={closeRef} className="modal-close" type="button" onClick={onClose} aria-label={t.close}>×</button><p className="eyebrow">{eyebrow}</p><h2 id="modal-title">{title}</h2>{children}</section></div>;
}

export default function App() {
  const [language, setLanguage] = useState(initialLanguage);
  const [user, setUser] = useState(null), [profile, setProfile] = useState(null), [ageRequest, setAgeRequest] = useState(null);
  const [modal, setModal] = useState(null), [mode, setMode] = useState("login"), [notice, setNotice] = useState(""), [busy, setBusy] = useState(true);
  const t = useMemo(() => window.SiteTranslations?.[language] || window.SiteTranslations.en, [language]);
  const refresh = async () => { const current = await getCurrentUser(); setUser(current); if (current) { const [member, age] = await Promise.all([getMemberProfile(current.$id), getAgeVerification(current.$id)]); setProfile(member); setAgeRequest(age); } else { setProfile(null); setAgeRequest(null); } };
  useEffect(() => { document.documentElement.lang = language; document.title = t.metaTitle; localStorage.setItem(languageKey, language); }, [language, t]);
  useEffect(() => { const p = new URLSearchParams(location.search); (async () => { try { if (p.get("action") === "verify-email" && p.get("userId") && p.get("secret")) { await completeEmailVerification(p.get("userId"), p.get("secret")); setNotice(t.emailVerified); history.replaceState({}, "", "/"); setModal("account"); } else if (p.get("action") === "recover") { setMode("recover"); setModal("auth"); } await refresh(); } catch (error) { setNotice(messageFor(error, t)); } finally { setBusy(false); } })(); }, []);
  const openAuth = (nextMode) => { setMode(nextMode); setNotice(""); setModal("auth"); };
  const run = async (work, success, nextModal) => { setBusy(true); setNotice(""); try { await work(); await refresh(); setNotice(success); if (nextModal) setModal(nextModal); } catch (error) { setNotice(messageFor(error, t)); } finally { setBusy(false); } };
  const handleAuth = (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); if (mode === "register") run(() => registerAccount(data), t.registrationSent, "account"); else if (mode === "reset") run(() => requestPasswordReset(data.email), t.resetSent); else if (mode === "recover") { const p = new URLSearchParams(location.search); run(() => completePasswordReset(p.get("userId"), p.get("secret"), data.password), t.passwordChanged); } else run(() => login(data.email, data.password), t.loginSuccess, "account"); };
  const handleAge = (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); run(() => submitAgeVerification(user, data), t.ageSubmitted, "account"); };
  const status = ageRequest?.status || profile?.ageVerificationStatus || (user ? "NOT_STARTED" : "SIGNED_OUT");

  return <>
    <div className="ember-field" aria-hidden="true" />
    <header className="exclusive-header"><a className="brand" href="#top">JS<span>.</span></a><nav className="main-nav desktop-nav" aria-label={t.navigation}><a href="#experience">{t.navProfile}</a><a href="#membership">{t.navExclusive}</a><a href="#access">{t.navAccess}</a></nav><div className="header-actions"><div className="language-switcher">{["de", "en"].map(lang => <button className={`language-button${lang === language ? " is-active" : ""}`} type="button" onClick={() => setLanguage(lang)} key={lang}>{lang.toUpperCase()}</button>)}</div><button className="secondary-action header-link" type="button" onClick={() => user ? setModal("account") : openAuth("login")}>{user ? t.account : t.login}</button></div></header>
    <main id="top">
      <section className="hero adult-hero"><div className="hero-media" aria-hidden="true"><img src="/linktree/uploads/banner.png" alt="" /><div className="hero-media__shade" /></div><div className="hero-content adult-hero__content"><p className="eyebrow">{t.adultsOnly}</p><h1>{t.heroTitle}</h1><p className="tagline">{t.heroText}</p><div className="hero-actions"><button className="primary-action" type="button" onClick={() => user ? setModal("account") : openAuth("register")}>{user ? t.account : t.register}</button><a className="secondary-action" href="#experience">{t.explore}</a></div><p className="trust-line"><span>18+</span> {t.trustLine}</p></div></section>
      <section id="experience" className="section intro-section"><div className="section-heading"><p className="eyebrow">{t.profileEyebrow}</p><h2>{t.introTitle}</h2><p>{t.bio}</p></div><div className="editorial-grid"><LockedCard t={t} wide /><div className="editorial-copy"><p className="eyebrow">{t.privateLabel}</p><h2>{t.privateTitle}</h2><p>{t.privateText}</p><a href="#membership" className="text-link">{t.discoverAccess} →</a></div></div></section>
      <section id="membership" className="section membership-section"><div className="section-heading"><p className="eyebrow">{t.accessPath}</p><h2>{t.howItWorks}</h2><p>{t.processIntro}</p></div><div className="tier-list"><Tier number="01" title={t.stepAccount} text={t.stepAccountText} /><Tier number="02" title={t.stepVerify} text={t.stepVerifyText} featured /><Tier number="03" title={t.stepAccess} text={t.stepAccessText} /></div></section>
      <section id="exclusive" className="section preview-section"><div className="section-heading"><p className="eyebrow">{t.curatedLabel}</p><h2>{t.exclusiveHeading}</h2><p>{t.exclusiveText}</p></div><div className="locked-grid"><LockedCard t={t} /><LockedCard t={t} /><LockedCard t={t} /></div></section>
      <section id="access" className="section access-section"><div><p className="eyebrow">{t.readyLabel}</p><h2>{t.readyTitle}</h2><p>{t.readyText}</p></div><div className="hero-actions"><button className="primary-action" type="button" onClick={() => user ? setModal("account") : openAuth("register")}>{user ? t.openDashboard : t.createAccount}</button><button className="secondary-action" type="button" onClick={() => user ? setModal("account") : openAuth("login")}>{user ? t.viewStatus : t.login}</button></div></section>
    </main>
    <footer id="legal" className="site-footer legal-footer"><div><a className="brand" href="#top">{t.brand}</a><p>{t.footerLive}</p></div><nav><a href="/legal/">{t.legalLink}</a></nav></footer>

    {modal === "auth" && <Modal title={mode === "register" ? t.createAccount : mode === "login" ? t.welcomeBack : t.reset} eyebrow={t.secureAccount} onClose={() => setModal(null)} t={t}><div className="auth-tabs">{["login", "register", "reset"].map(item => <button type="button" className={mode === item ? "is-active" : ""} onClick={() => { setMode(item); setNotice(""); }} key={item}>{t[item]}</button>)}</div>{notice && <p className="form-notice" role="status">{notice}</p>}<form className="auth-panel" onSubmit={handleAuth}>{mode === "register" && <Field label={t.name} name="name" autoComplete="name" required maxLength="128" />}{mode !== "recover" && <Field label={t.emailLabel} name="email" type="email" autoComplete="email" required />}{mode !== "reset" && <Field label={t.password} name="password" type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} minLength="8" required />}<button className="primary-action" disabled={busy}>{busy ? t.loading : t[`${mode}Submit`]}</button></form></Modal>}
    {modal === "account" && <Modal title={t.account} eyebrow={status} onClose={() => setModal(null)} t={t}>{notice && <p className="form-notice" role="status">{notice}</p>}{!user ? <button className="primary-action" onClick={() => openAuth("login")}>{t.login}</button> : <div className="dashboard"><dl><div><dt>{t.emailLabel}</dt><dd>{user.email}</dd></div><div><dt>{t.statusLabel}</dt><dd>{profile?.status || "EMAIL_PENDING"}</dd></div><div><dt>{t.avsLabel}</dt><dd>{status}</dd></div></dl><div className="dashboard-actions">{!user.emailVerification && <button className="secondary-action" onClick={() => run(resendVerification, t.verificationSent)}>{t.resendVerification}</button>}<button className="primary-action" disabled={!user.emailVerification || status === "MANUAL_REVIEW_PENDING"} onClick={() => setModal("age")}>{status === "MANUAL_REVIEW_PENDING" ? t.reviewPending : t.avsStart}</button><button className="text-button" onClick={() => run(logout, t.logoutSuccess, "auth")}>{t.logout}</button></div></div>}</Modal>}
    {modal === "age" && <Modal title={t.ageFormTitle} eyebrow={t.stepVerify} onClose={() => setModal("account")} t={t}><p className="modal-intro">{t.ageFormText}</p>{notice && <p className="form-notice" role="status">{notice}</p>}<form className="auth-panel" onSubmit={handleAge}><Field label={t.legalName} name="legalName" autoComplete="name" required maxLength="128" /><Field label={t.birthDate} name="birthDate" type="date" required /><Field label={t.country} name="country" required minLength="2" maxLength="2" placeholder="DE" /><label className="check-field"><input type="checkbox" required /> <span>{t.ageDeclaration}</span></label><button className="primary-action" disabled={busy}>{busy ? t.loading : t.submitReview}</button></form></Modal>}
  </>;
}
